version: '1.1'

services:
  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki.yaml:/etc/loki.yaml
    command: -config.file=/etc/loki.yaml
  
  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./configs/promtail.yaml:/etc/promtail.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail.yaml

  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317:4317"
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.144.0 
    container_name: otel-collector
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./configs/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"  

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    volumes:
      - grafana-data:/data/grafana

    ports:
      - "3001:3000"    
    depends_on:
      - loki
      - promtail
      - tempo
      - otel-collector

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-otlp-receiver'
      - '--enable-feature=exemplar-storage'
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
  backend-api:
    image: backend-api
    container_name: backend-api
    environment:
      - OTEL_EXPORTER_URL=http://otel-collector:4318/v1/traces
    ports:
      - "8000:8000"      

volumes:
  grafana-data:
  prometheus-data: